export const siteContent = {
  ui: {
    beforeLabel: "Sebelum",
    afterLabel: "Sesudah",
    compareHint: "Geser untuk membandingkan",
    previous: "Sebelumnya",
    next: "Berikutnya",
    openMenu: "Buka menu navigasi",
    closeMenu: "Tutup menu navigasi",
    viewOnMaps: "Buka lokasi di Google Maps",
    selected: "dipilih",
    pricePrefix: "mulai dari",
    treatmentQuestion: "Tanya via WhatsApp",
    doctorQuestion: "Tanya jadwal",
    testimonialTabs: "Pilih cerita pasien",
    floatingCare: "Care\nwith\nclarity",
    testimonialPosition: "Cerita pasien",
    mainNavigation: "Navigasi utama",
    mobileNavigation: "Navigasi mobile",
    instagramLabel: "Instagram Lumière",
    tiktokLabel: "TikTok Lumière",
    whatsappLabel: "WhatsApp Lumière",
    trustDisclaimer: "Badge dan angka pada halaman ini adalah contoh demo; verifikasi sebelum digunakan untuk klinik nyata.",
    branchTabs: "Pilih cabang Lumière",
  },
  brand: {
    name: "Lumière",
    descriptor: "Aesthetic Clinic",
    tagline: "Perawatan yang terasa personal.",
    whatsapp: "6281212345678",
    whatsappLabel: "Konsultasi via WhatsApp",
    instagram: "https://instagram.com/lumiere.aesthetic",
    tiktok: "https://tiktok.com/@lumiere.aesthetic",
  },
  messages: {
    treatment: "Halo Lumière, saya ingin bertanya tentang",
    doctor: "Halo Lumière, saya ingin berkonsultasi dengan tim dokter.",
  },
  nav: [
    { label: "Treatment", href: "#treatment" },
    { label: "Dokter", href: "#dokter" },
    { label: "Cabang", href: "#cabang" },
    { label: "Cerita pasien", href: "#testimoni" },
    { label: "FAQ", href: "#faq" },
  ],
  hero: {
    eyebrow: "Klinik estetika medis · Jakarta Selatan",
    title: "Mulai dari kulitmu,\nbukan dari tren.",
    description:
      "Setiap kulit punya kebutuhan yang berbeda. Di Lumière, kamu bisa berkonsultasi dulu dan menyusun langkah perawatan bersama dokter.",
    primaryCta: "Mulai konsultasi",
    secondaryCta: "Lihat treatment",
    trustNote: "Dokter berlisensi · Klinik berizin",
    whatsappMessage: "Halo Lumière, saya ingin memulai konsultasi.",
    image: {
      src: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1400&q=88",
      alt: "Dokter perempuan tersenyum saat berkonsultasi di ruang klinik yang hangat",
    },
    detailImage: {
      src: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=700&q=85",
      alt: "Detail perawatan kulit dengan suasana tenang",
    },
  },
  trust: [
    { value: "4.9", suffix: "/5", label: "Rating Google", icon: "star" },
    { value: "✓", suffix: "", label: "Dokter Berlisensi*", icon: "shield" },
    { value: "✓", suffix: "", label: "Klinik Berizin*", icon: "shield" },
    { value: "1:1", suffix: "", label: "Konsultasi personal", icon: "sparkle" },
  ],
  faqHeading: { eyebrow: "Pertanyaan umum", title: "Hal-hal yang mungkin ingin kamu tahu.", description: "Kalau masih ada yang ingin dibicarakan, tim kami siap menjawab lewat WhatsApp." },
  treatments: [
    { name: "Botox", category: "Ekspresi wajah", description: "Untuk membahas tampilan garis ekspresi dengan dokter dan memilih langkah yang sesuai.", price: "Rp1.500.000", image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=85", alt: "Terapis melakukan perawatan wajah pada pasien di ruang klinik" },
    { name: "Dermal Filler", category: "Kontur wajah", description: "Konsultasi untuk memahami proporsi wajah dan pilihan perawatan kontur secara menyeluruh.", price: "Rp3.500.000", image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=800&q=85", alt: "Dokter berkonsultasi dengan pasien sebelum perawatan wajah" },
    { name: "Laser", category: "Kesehatan kulit", description: "Perawatan dengan perangkat laser setelah dokter memahami kondisi dan kebutuhan kulitmu.", price: "Rp1.250.000", image: "https://images.pexels.com/photos/4586726/pexels-photo-4586726.jpeg?h=1000&w=1500&fit=crop", alt: "Kosmetolog melakukan perawatan laser pada wajah pasien" },
    { name: "Chemical Peel", category: "Tekstur kulit", description: "Aplikasi perawatan pada permukaan kulit dengan formula dan intensitas yang disesuaikan.", price: "Rp850.000", image: "https://images.pexels.com/photos/5069432/pexels-photo-5069432.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Tenaga medis mengaplikasikan chemical peel pada wajah pasien" },
    { name: "Hydrainfuse", category: "Hidrasi kulit", description: "Perawatan facial yang membantu kulit terasa lebih segar, lembap, dan nyaman.", price: "Rp1.100.000", image: "https://images.pexels.com/photos/5069612/pexels-photo-5069612.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Perangkat hydrodermabrasion digunakan pada dahi pasien" },
    { name: "Skin Booster", category: "Kualitas kulit", description: "Pilihan perawatan untuk membahas tampilan kulit yang terasa kurang kenyal bersama dokter.", price: "Rp2.750.000", image: "https://images.unsplash.com/photo-1552693673-1bf958298935?auto=format&fit=crop&w=800&q=85", alt: "Dokter memeriksa kondisi kulit pasien sebelum menentukan perawatan" },
  ],
  sectionHeadings: {
    treatments: { eyebrow: "Pilihan perawatan", title: "Cari tahu mana yang cocok untukmu.", description: "Lihat beberapa treatment yang tersedia di Lumière. Tidak perlu langsung memilih; kita bisa mulai dari ngobrol bersama dokter." },
    doctors: { eyebrow: "Orang di balik Lumière", title: "Dokter yang hadir untuk mendengarkan.", description: "Kenali tim dokter kami yang percaya bahwa perawatan estetika dimulai dari konsultasi yang jujur dan nyaman." },
    reasons: { eyebrow: "Kenapa Lumière", title: "Kredibel untuk dipilih. Hangat untuk didatangi.", description: "Kami menjaga keseimbangan antara standar medis dan pengalaman yang terasa manusiawi." },
    testimonials: { eyebrow: "Cerita dari ruang konsultasi", title: "Pengalaman yang terasa personal.", description: "Cerita berikut menggambarkan pengalaman layanan dan suasana. Setiap perjalanan kulit tetap unik." },
  },
  comparisons: [
    { label: "Tekstur kulit", note: "Placeholder hasil facial treatment, bukan dokumentasi pasien", before: "https://images.pexels.com/photos/9253761/pexels-photo-9253761.jpeg?auto=compress&cs=tinysrgb&w=1200", after: "https://images.pexels.com/photos/9253767/pexels-photo-9253767.jpeg?auto=compress&cs=tinysrgb&w=1200", altBefore: "Placeholder close-up wajah dengan tekstur dan bintik kulit yang terlihat", altAfter: "Placeholder close-up wajah dengan tekstur kulit yang tampak lebih tenang" },
    { label: "Bekas jerawat", note: "Placeholder hasil facial treatment, bukan dokumentasi pasien", before: "https://images.pexels.com/photos/9253761/pexels-photo-9253761.jpeg?auto=compress&cs=tinysrgb&w=1200", after: "https://images.pexels.com/photos/9253767/pexels-photo-9253767.jpeg?auto=compress&cs=tinysrgb&w=1200", altBefore: "Placeholder close-up pipi dengan bekas jerawat yang terlihat", altAfter: "Placeholder close-up pipi dengan tampilan bekas jerawat yang lebih samar" },
    { label: "Complexion", note: "Placeholder hasil facial treatment, bukan dokumentasi pasien", before: "https://images.pexels.com/photos/6475987/pexels-photo-6475987.jpeg?auto=compress&cs=tinysrgb&w=1200", after: "https://images.pexels.com/photos/9253774/pexels-photo-9253774.jpeg?auto=compress&cs=tinysrgb&w=1200", altBefore: "Placeholder close-up wajah dengan warna kulit dan tekstur yang tidak merata", altAfter: "Placeholder close-up wajah dengan tampilan complexion yang lebih merata" },
  ],
  showcase: {
    eyebrow: "Perjalanan kulit",
    title: "Contoh visual, bukan janji hasil.",
    description: "Geser untuk melihat perbedaan visual pada placeholder template ini. Dokumentasi pasien nyata harus memakai persetujuan dan data yang terverifikasi; hasil dapat berbeda tiap individu.",
  },
  doctors: [
    { name: "dr. Amalia Putri", title: "Sp.DVE", specialty: "Dermatologi & Venereologi Estetik", description: "Mendengarkan kebutuhan kulit dengan teliti dan menyusun perawatan yang realistis.", image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=85", alt: "dr. Amalia Putri mengenakan jas putih" },
    { name: "dr. Raka Pradana", title: "M.Kes", specialty: "Estetika Medis", description: "Mengutamakan komunikasi terbuka dan proses perawatan yang nyaman.", image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=85", alt: "dr. Raka Pradana tersenyum di klinik" },
    { name: "dr. Nadine Larasati", title: "Sp.DV", specialty: "Dermatologi Klinis", description: "Membantu pasien memahami pilihan perawatan sesuai kondisi kulitnya.", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=900&q=85", alt: "dr. Nadine Larasati di ruang konsultasi" },
  ],
  reasons: [
    { title: "Konsultasi yang didengar", description: "Setiap rencana dimulai dari percakapan, bukan asumsi.", icon: "chat" },
    { title: "Harga yang transparan", description: "Perkiraan biaya dibahas sejak awal supaya kamu bisa memilih dengan tenang.", icon: "receipt" },
    { title: "Ruang yang menenangkan", description: "Detail kecil dirancang untuk membuat kunjungan pertama terasa lebih ringan.", icon: "leaf" },
    { title: "Pendampingan yang jelas", description: "Kami menjelaskan perawatan dan langkah setelahnya dengan bahasa yang mudah dipahami.", icon: "path" },
  ],
  testimonials: [
    { quote: "Dari pertama datang, penjelasannya terasa jelas dan tidak terburu-buru. Ruangnya juga tenang.", name: "Nadia A.", detail: "Konsultasi kulit", initials: "NA" },
    { quote: "Aku suka karena timnya mendengarkan kekhawatiranku dulu. Jadi lebih nyaman menentukan pilihan perawatan.", name: "Salsa R.", detail: "Perawatan wajah", initials: "SR" },
    { quote: "Booking lewat WhatsApp cepat, lalu di klinik semua alurnya dijelaskan dengan ramah.", name: "Maya P.", detail: "Kunjungan pertama", initials: "MP" },
    { quote: "Interiornya hangat dan stafnya sangat membantu. Pengalaman konsultasinya terasa personal.", name: "Dina K.", detail: "Konsultasi dokter", initials: "DK" },
  ],
  clinic: {
    heading: {
      eyebrow: "Suasana Lumière",
      title: "Ruang yang membuat kunjungan terasa lebih mudah.",
      description: "Mulai dari area tunggu hingga ruang konsultasi, setiap sudut Lumière dibuat agar kamu bisa datang, bertanya, dan menjalani perawatan dengan lebih nyaman.",
    },
    images: [
      { src: "https://images.pexels.com/photos/36000439/pexels-photo-36000439/free-photo-of-modern-hospital-building-in-harare-zimbabwe.jpeg", alt: "Tampak luar gedung klinik modern dengan akses masuk yang jelas" },
      { src: "https://images.pexels.com/photos/33812025/pexels-photo-33812025.jpeg", alt: "Meja resepsionis klinik dengan interior modern dan aksen kayu" },
      { src: "https://images.pexels.com/photos/8459996/pexels-photo-8459996.jpeg", alt: "Ruang tunggu klinik dengan sofa dan dekorasi yang terang" },
      { src: "https://images.pexels.com/photos/36930338/pexels-photo-36930338/free-photo-of-skincare-procedure-in-modern-aesthetic-clinic.jpeg", alt: "Prosedur skincare berlangsung di ruang aesthetic clinic modern" },
    ],
    branches: [
      { name: "Senopati", address: "Jl. Senopati No. 18, Kebayoran Baru, Jakarta Selatan", hours: "Senin–Sabtu · 09.00–20.00 WIB", maps: "https://maps.google.com/?q=Lumiere+Aesthetic+Clinic+Senopati" },
      { name: "Alam Sutera", address: "Jl. Jalur Sutera No. 28, Tangerang Selatan", hours: "Senin–Sabtu · 09.00–20.00 WIB", maps: "https://maps.google.com/?q=Lumiere+Aesthetic+Clinic+Alam+Sutera" },
      { name: "Kelapa Gading", address: "Jl. Boulevard Raya No. 8, Jakarta Utara", hours: "Senin–Sabtu · 09.00–20.00 WIB", maps: "https://maps.google.com/?q=Lumiere+Aesthetic+Clinic+Kelapa+Gading" },
    ],
  },
  faq: [
    { question: "Apakah saya perlu konsultasi sebelum memilih treatment?", answer: "Ya. Konsultasi membantu dokter memahami kondisi dan tujuan perawatanmu sebelum merekomendasikan pilihan yang sesuai. Treatment tidak harus dilakukan di hari yang sama." },
    { question: "Berapa biaya konsultasi di Lumière?", answer: "Konsultasi awal tersedia tanpa biaya untuk periode demo ini. Estimasi treatment akan dijelaskan secara terbuka setelah kebutuhanmu dipahami." },
    { question: "Apakah semua treatment cocok untuk setiap orang?", answer: "Belum tentu. Kondisi kulit, riwayat kesehatan, dan tujuan setiap orang berbeda. Dokter akan membantu menjelaskan opsi yang relevan dan batasannya." },
    { question: "Bagaimana cara membuat janji?", answer: "Klik tombol WhatsApp di halaman ini dan kirim pesan yang sudah disiapkan. Tim kami akan membantu mencari waktu kunjungan yang tersedia." },
    { question: "Apa yang perlu disiapkan untuk kunjungan pertama?", answer: "Cukup datang dengan wajah bersih bila memungkinkan dan ceritakan produk atau perawatan yang sedang digunakan. Informasi ini membantu konsultasi berjalan lebih nyaman." },
    { question: "Apakah hasil perawatan akan sama untuk semua orang?", answer: "Tidak. Respons kulit dapat berbeda pada tiap individu. Kami akan membicarakan ekspektasi secara realistis sebelum perawatan dimulai." },
  ],
  finalCta: {
    eyebrow: "Waktunya mengenal kulitmu",
    title: "Boleh mulai dari tanya-tanya dulu.",
    description: "Ceritakan apa yang sedang kamu cari lewat WhatsApp. Tim Lumière akan membantu menjelaskan pilihan dan langkah pertamanya.",
    button: "Tanya dulu via WhatsApp",
    note: "Tidak harus langsung treatment. Hasil dapat berbeda tiap individu.",
    whatsappMessage: "Halo Lumière, saya ingin tanya-tanya dulu tentang perawatan yang sesuai untuk saya.",
  },
  footer: {
    description: "Perawatan estetika yang terasa personal.",
    copyright: "© 2026 Lumière Aesthetic Clinic. Website demo untuk kebutuhan portfolio.",
    demoLabel: "Template demo · Lumière",
    links: ["Treatment", "Dokter", "Cabang", "Cerita Pasien","FAQ"],
  },
} as const;

export function whatsappUrl(message = "Halo Lumière, saya ingin berkonsultasi tentang perawatan kulit.") {
  return `https://wa.me/${siteContent.brand.whatsapp}?text=${encodeURIComponent(message)}`;
}
